services:
  postgres:
    image: postgres:15
    container_name: heatnet-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  digital-twin-backend:
    build:
      context: ./digital-twin-backend
      dockerfile: Dockerfile
    container_name: heatnet-backend
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@postgres:5432/postgres
    restart: always

volumes:
  postgres_data: